// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "PrintSimple\App.config"
//     Connection String Name: "printsimpleEntities"
//     Connection String:      "metadata=res://*/printsimple.csdl|res://*/printsimple.ssdl|res://*/printsimple.msl;provider=System.Data.SqlServerCe.4.0;provider connection string="Data Source=D:\Onedrive\dropbox\Visual Studio 2015\newcode\PrintSimple\PrintSimple\bin\printsimple.sdf""
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// Failed to load provider "System.Data.EntityClient" - Unable to find the requested .Net Framework Data Provider.  It may not be installed.
// ------------------------------------------------------------------------------------------------

