//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintSimple
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbPrintSimpleEntities : DbContext
    {
        public dbPrintSimpleEntities()
            : base("name=dbPrintSimpleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCacheUpdate> tblCacheUpdates { get; set; }
        public virtual DbSet<tblMatchedDriver> tblMatchedDrivers { get; set; }
        public virtual DbSet<tblPrinterClassCache> tblPrinterClassCaches { get; set; }
        public virtual DbSet<tblPrinterDriverCache> tblPrinterDriverCaches { get; set; }
        public virtual DbSet<tblPrinterTCPIPClassCache> tblPrinterTCPIPClassCaches { get; set; }
    }
}
