//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintSimple
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrinterTCPIPClassCache
    {
        public int ID { get; set; }
        public string PortName { get; set; }
        public string PortAddress { get; set; }
        public string CacheGUID { get; set; }
        public string PrintServer { get; set; }
    }
}
